Repository DDD-4/Spark-iOS, pull requests merged in 2020-09, with the labels that each got.

#73 update TakePictureViewController UI
  Vocabulary/AddWord/TakePictureController.swift
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/btnClose.png
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/btnClose@2x.png
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/btnClose@3x.png
  Vocabulary/Resource/Assets.xcassets/iconCamera.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/iconCamera.imageset/iconCamera.png
  Vocabulary/Resource/Assets.xcassets/iconCamera.imageset/iconCamera@2x.png
  Vocabulary/Resource/Assets.xcassets/iconCamera.imageset/iconCamera@3x.png
Labels: UI

#74 [1.0.0] update VocaForAll UI
  Vocabulary/Resource/Assets.xcassets/icAdd.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icAdd.imageset/icAdd.png
  Vocabulary/Resource/Assets.xcassets/icAdd.imageset/icAdd@2x.png
  Vocabulary/Resource/Assets.xcassets/icAdd.imageset/icAdd@3x.png
  Vocabulary/Resource/Assets.xcassets/iconClose.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/iconClose.imageset/iconClose.png
  Vocabulary/Resource/Assets.xcassets/iconClose.imageset/iconClose@2x.png
  Vocabulary/Resource/Assets.xcassets/iconClose.imageset/iconClose@3x.png
  Vocabulary/VacoForAll/Detail/DummyVocaDetailViewController.swift
  Vocabulary/VacoForAll/Detail/SelectFolderViewCell.swift
  Vocabulary/VacoForAll/Detail/SelectFolderViewController.swift
Labels: UI

#77 [#76] Add Order Attribute in word, group
  PoingVocaSubsystem/DummyData/DummyData.swift
  PoingVocaSubsystem/LoadCoreDataManager.swift
  PoingVocaSubsystem/ManagedGroup+CoreDataProperties.swift
  PoingVocaSubsystem/ManagedWord+CoreDataProperties.swift
  PoingVocaSubsystem/Voca.xcdatamodeld/Voca.xcdatamodel/contents
  PoingVocaSubsystem/VocaDownload/VocaDownloadOperation.swift
  PoingVocaSubsystem/VocaManager.swift
  PoingVocaSubsystemTests/PoingVocaSubsystemTests.swift
  VocaGame/Matching/CardMatchingViewController.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/AddWordViewController.swift
  Vocabulary/AddWord/TakePictureController.swift
  Vocabulary/Game/GameViewController.swift
  Vocabulary/MyVoca/AddFolderViewController.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/Setting/SettingViewController.swift
  Vocabulary/VacoForAll/Detail/WordViewModel.swift
Labels: 🧾 기능개발

#79 Add Login, signin UI
  PoingDesignSystem/AccentLineTextField.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AppDelegate.swift
  Vocabulary/Login/AppleLoginButton.swift
  Vocabulary/Login/AppleLoginHelper.swift
  Vocabulary/Login/LoginViewController.swift
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/iconApple.png
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/iconApple@2x.png
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/iconApple@3x.png
  Vocabulary/SignIn/SignInNameViewController.swift
  Vocabulary/Utills/UITapGestureRecognizer+.swift
  Vocabulary/Vocabulary.entitlements
Labels: UI, 🧾 기능개발

#82 [#81] change isSelected to isEnabled
  Vocabulary/AddWord/AddWordViewController.swift
  Vocabulary/MyVoca/AddFolderViewController.swift
  Vocabulary/SignIn/SignInNameViewController.swift
Labels: 🐛 버그

#80 connect ViewModel and Disconnect DummyData
  PoingDesignSystem/SelectFolderButton.swift
  PoingVocaSubsystem/VocaManager.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/AddWord/SelectVocaViewController.swift
  Vocabulary/AddWord/TakePictureController.swift
  Vocabulary/AppDelegate.swift
  Vocabulary/MyVoca/AddFolderViewController.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/VocaForAllViewModel.swift
  Vocabulary/SignIn/SignInNameViewController.swift
  Vocabulary/VacoForAll/Detail/SelectFolderViewCell.swift
  Vocabulary/VacoForAll/Detail/SelectFolderViewController.swift
  Vocabulary/VacoForAll/Detail/VocaDetailViewController.swift
  Vocabulary/VacoForAll/Detail/WordDetailCell.swift
  Vocabulary/VacoForAll/Detail/WordViewModel.swift
  Vocabulary/VacoForAll/VocaForAllCell.swift
  Vocabulary/VocaForAll/VocaForAllViewController.swift
  Vocabulary/Vocabulary.entitlements
Labels: Refactoring

#83 [Fix Bug]
  Vocabulary/AddWord/DetailWordViewController.swift
Labels: 🐛 버그

#85 [#84] VocaForAll Network
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Moya/Sources/RxMoya/MoyaProvider+Rx.swift
  Pods/Moya/Sources/RxMoya/Observable+Response.swift
  Pods/Moya/Sources/RxMoya/Single+Response.swift
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Moya/Moya.xcconfig
  Pods/Target Support Files/Pods-PoingVocaSubsystem/Pods-PoingVocaSubsystem-acknowledgements.markdown
  Pods/Target Support Files/Pods-PoingVocaSubsystem/Pods-PoingVocaSubsystem-acknowledgements.plist
  Pods/Target Support Files/Pods-PoingVocaSubsystem/Pods-PoingVocaSubsystem.debug.xcconfig
  Pods/Target Support Files/Pods-PoingVocaSubsystem/Pods-PoingVocaSubsystem.release.xcconfig
  PoingVocaSubsystem/Network/EveryVocaResponse.swift
  PoingVocaSubsystem/Network/EveryVocabularyController.swift
  PoingVocaSubsystem/Network/EveryVocabularyService.swift
  PoingVocaSubsystem/Network/Utills/BaseManager.swift
  PoingVocaSubsystem/Network/WordResponse.swift
  PoingVocaSubsystem/VocaDownload/VocaDownloadAgent.swift
  PoingVocaSubsystem/VocaDownload/VocaDownloadOperation.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/AddWord/SelectViewModel.swift
  Vocabulary/AddWord/SelectVocaViewController.swift
  Vocabulary/AppDelegate.swift
  Vocabulary/Info.plist
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/VocaForAllViewModel.swift
  Vocabulary/VacoForAll/Detail/DummyVocaDetailViewController.swift
  Vocabulary/VacoForAll/Detail/WordViewModel.swift
  Vocabulary/VacoForAll/SelectFolderViewCell.swift
  Vocabulary/VacoForAll/SelectFolderViewController.swift
  Vocabulary/VacoForAll/VocaForAllCell.swift
  Vocabulary/VacoForAll/VocaForAllDetailViewController.swift
  Vocabulary/VacoForAll/VocaHeaderView.swift
  Vocabulary/VacoForAll/WordDetailCell.swift
  Vocabulary/VacoForAll/WordViewModel.swift
  Vocabulary/Vocabulary.entitlements
Labels: 🧾 기능개발

#92 [#91] Online, Offline Sync
  PoingVocaSubsystem/ManagedGroup+CoreDataProperties.swift
  PoingVocaSubsystem/ManagedWord+CoreDataProperties.swift
  PoingVocaSubsystem/Network/EveryVocabularyController.swift
  PoingVocaSubsystem/Network/EveryVocabularyService.swift
  PoingVocaSubsystem/Network/Folder.swift
  PoingVocaSubsystem/Network/FolderController.swift
  PoingVocaSubsystem/Network/FolderService.swift
  PoingVocaSubsystem/Network/Utills/ServerURL.swift
  PoingVocaSubsystem/Network/Word.swift
  PoingVocaSubsystem/Network/WordResponse.swift
  PoingVocaSubsystem/VocaCoreDataManager.swift
  PoingVocaSubsystem/VocaDownload/VocaDownloadAgent.swift
  PoingVocaSubsystem/VocaDownload/VocaDownloadOperation.swift
  PoingVocaSubsystem/VocaManager.swift
  PoingVocaSubsystemTests/PoingVocaSubsystemTests.swift
  VocaGame/Flip/Controllers/FlipGameViewController.swift
  VocaGame/Matching/CardMatchingViewController.swift
  VocaGame/ProgressBarNavigationView.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/AddWord/SelectViewModel.swift
  Vocabulary/AddWord/SelectVocaTableViewCell.swift
  Vocabulary/AddWord/SelectVocaViewController.swift
  Vocabulary/Game/GameViewController.swift
  Vocabulary/Info.plist
  Vocabulary/MyVoca/EditMyVocaGroupViewModel.swift
  Vocabulary/MyVoca/HomeViewController.swift
  Vocabulary/MyVoca/MyVocaGroupReusableView.swift
  Vocabulary/MyVoca/MyVocaOnlineViewModel.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaViewModel.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/MyVoca/VocaForAllViewModel.swift
  Vocabulary/Setting/EditMyFolderOnlineViewModel.swift
  Vocabulary/Setting/EditMyVocaFolderCell.swift
  Vocabulary/Setting/EditMyVocaFolderViewController.swift
  Vocabulary/Setting/EditMyVocaFolderViewModel.swift
  Vocabulary/Setting/MyFolderDetailOnlineViewModel.swift
  Vocabulary/Setting/MyFolderDetailViewController.swift
  Vocabulary/Setting/MyFolderDetailViewModel.swift
  Vocabulary/Setting/SettingViewController.swift
  Vocabulary/Utills/ModeConfig.swift
  Vocabulary/Utills/ModeConfigStateView.swift
  Vocabulary/Utills/Notification.Name+.swift
  Vocabulary/VacoForAll/SelectFolderViewCell.swift
  Vocabulary/VacoForAll/SelectFolderViewController.swift
  Vocabulary/VacoForAll/VocaForAllCell.swift
  Vocabulary/VacoForAll/VocaForAllDetailViewController.swift
  Vocabulary/VacoForAll/VocaForAllDetailViewModel.swift
  Vocabulary/VacoForAll/WordDetailCell.swift
  Vocabulary/VacoForAll/WordViewModel.swift
Labels: Refactoring

#96 [#95] 내 프로필 편집 UI Fix
  Vocabulary/Setting/MyProfileViewController.swift
  Vocabulary/Setting/SettingViewController.swift
Labels: UI, 🐛 버그

#94 [#93] Fix 단어 추가/수정 UI
  Vocabulary/AddWord/DetailWordViewController.swift
Labels: UI, 🐛 버그

#100 [#99] Add Score UI
  PoingDesignSystem/CALayer+.swift
  PoingDesignSystem/UIColor+.swift
  VocaGame/Matching/CardMatchingViewController.swift
  VocaGame/Media.xcassets/imageFail.imageset/Contents.json
  VocaGame/Media.xcassets/imageFail.imageset/imageFail.png
  VocaGame/Media.xcassets/imageFail.imageset/imageFail@2x.png
  VocaGame/Media.xcassets/imageFail.imageset/imageFail@3x.png
  VocaGame/Media.xcassets/imageSuccess.imageset/Contents.json
  VocaGame/Media.xcassets/imageSuccess.imageset/imageSuccess.png
  VocaGame/Media.xcassets/imageSuccess.imageset/imageSuccess@2x.png
  VocaGame/Media.xcassets/imageSuccess.imageset/imageSuccess@3x.png
  VocaGame/ScoreAnimateView.swift
  Vocabulary.xcodeproj/project.pbxproj
Labels: UI, 🧾 기능개발

#98 [1.0.0] add mic Animation
  PoingDesignSystem/PulseAnimation.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/icVoice.png
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/icVoice@2x.png
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/icVoice@3x.png
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/icVoiceSpeaking.png
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/icVoiceSpeaking@2x.png
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/icVoiceSpeaking@3x.png
Labels: UI

#103 [#101][VocaGame] Confetti Animation, Folder Select ViewController
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame-acknowledgements.markdown
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame-acknowledgements.plist
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame.debug.xcconfig
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame.release.xcconfig
  PoingDesignSystem/RadioButton.swift
  PoingDesignSystem/UIColor+.swift
  PoingVocaSubsystem/Network/EveryVocaResponse.swift
  PoingVocaSubsystem/Network/EveryVocabularyController.swift
  PoingVocaSubsystem/Network/EveryVocabularyService.swift
  PoingVocaSubsystem/Network/Folder.swift
  VocaGame/ConfettiAnimation/ConfettiView.swift
  VocaGame/Flip/Controllers/FlipGameViewController.swift
  VocaGame/Flip/Model/CardsDataModel.swift
  VocaGame/Flip/View/FlipCardView.swift
  VocaGame/GameCompleteViewController.swift
  VocaGame/GameType.swift
  VocaGame/Matching/CardMatchingViewController.swift
  VocaGame/Matching/Model/CardMatching.swift
  VocaGame/Media.xcassets/confetti.imageset/3.png
  VocaGame/Media.xcassets/confetti.imageset/3@2x.png
  VocaGame/Media.xcassets/confetti.imageset/3@3x.png
  VocaGame/Media.xcassets/confetti.imageset/Contents.json
  VocaGame/Media.xcassets/yellowFaceWithChat.imageset/Contents.json
  VocaGame/Media.xcassets/yellowFaceWithChat.imageset/yellowFaceWithChat.png
  VocaGame/Media.xcassets/yellowFaceWithChat.imageset/yellowFaceWithChat@2x.png
  VocaGame/Media.xcassets/yellowFaceWithChat.imageset/yellowFaceWithChat@3x.png
  VocaGame/SelectFolderCell.swift
  VocaGame/SelectFolderViewController.swift
  VocaGame/SelectFolderViewModel.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Game/GameViewController.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/MyVoca/VocaForAllViewModel.swift
  Vocabulary/Resource/Assets.xcassets/selectorNormal.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/selectorNormal.imageset/selectorNormal.png
  Vocabulary/Resource/Assets.xcassets/selectorNormal.imageset/selectorNormal@2x.png
  Vocabulary/Resource/Assets.xcassets/selectorNormal.imageset/selectorNormal@3x.png
  Vocabulary/Resource/Assets.xcassets/selectorSelected.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/selectorSelected.imageset/selectorSelected.png
  Vocabulary/Resource/Assets.xcassets/selectorSelected.imageset/selectorSelected@2x.png
  Vocabulary/Resource/Assets.xcassets/selectorSelected.imageset/selectorSelected@3x.png
  Vocabulary/Utills/ModeConfig.swift
  Vocabulary/Utills/ModeConfigStateView.swift
  Vocabulary/Utills/Notification.Name+.swift
  Vocabulary/Vocabulary.entitlements
Labels: UI, 🧾 기능개발
