Repository DDD-4/Spark-iOS, pull requests merged in 2020-10, with the labels that each got.

#106 [#105] Design QA
  Vocabulary/Game/GameViewController.swift
Labels: UI

#104 [#87] every voca, evey voca detail pagination, miner model update
  PoingVocaSubsystem/ManagedGroup+CoreDataProperties.swift
  PoingVocaSubsystem/Network/EveryVocaResponse.swift
  PoingVocaSubsystem/Network/EveryVocabularyController.swift
  PoingVocaSubsystem/Network/EveryVocabularyService.swift
  PoingVocaSubsystem/Network/Folder.swift
  PoingVocaSubsystem/Network/Word.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/SelectFolderOnlineViewModel.swift
  Vocabulary/AddWord/SelectViewModel.swift
  Vocabulary/MyVoca/MyVocaGroupReusableView.swift
  Vocabulary/MyVoca/MyVocaOnlineViewModel.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/VocaForAllViewModel.swift
  Vocabulary/Setting/EditMyFolderOnlineViewModel.swift
  Vocabulary/Setting/EditMyVocaFolderViewController.swift
  Vocabulary/Setting/EditMyVocaFolderViewModel.swift
  Vocabulary/Setting/MyFolderDetailViewController.swift
  Vocabulary/VacoForAll/SelectFolderViewCell.swift
  Vocabulary/VacoForAll/SelectFolderViewController.swift
  Vocabulary/VacoForAll/VocaForAllDetailViewController.swift
  Vocabulary/VacoForAll/VocaForAllDetailViewModel.swift
Labels: 🧾 기능개발

#109 [#108] Apply App Icon, Splash Screen, Login
  Vocabulary/Base.lproj/LaunchScreen.storyboard
  Vocabulary/Login/LoginViewController.swift
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Vocabulary/Resource/Assets.xcassets/doughnut.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/doughnut.imageset/doughnut.png
  Vocabulary/Resource/Assets.xcassets/doughnut.imageset/doughnut@2x.png
  Vocabulary/Resource/Assets.xcassets/doughnut.imageset/doughnut@3x.png
  Vocabulary/Resource/Assets.xcassets/duck.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/duck.imageset/duck.png
  Vocabulary/Resource/Assets.xcassets/duck.imageset/duck@2x.png
  Vocabulary/Resource/Assets.xcassets/duck.imageset/duck@3x.png
  Vocabulary/Resource/Assets.xcassets/logoPoingpoing.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/logoPoingpoing.imageset/logoPoingpoing.png
  Vocabulary/Resource/Assets.xcassets/logoPoingpoing.imageset/logoPoingpoing@2x.png
  Vocabulary/Resource/Assets.xcassets/logoPoingpoing.imageset/logoPoingpoing@3x.png
Labels: UI

#111 Apply Image for GameViewController
  VocaGame/GameType.swift
  Vocabulary/Game/GameCell.swift
  Vocabulary/Game/GameViewController.swift
  Vocabulary/Resource/Assets.xcassets/icnMatching.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icnMatching.imageset/icnMatching.png
  Vocabulary/Resource/Assets.xcassets/icnMatching.imageset/icnMatching@2x.png
  Vocabulary/Resource/Assets.xcassets/icnMatching.imageset/icnMatching@3x.png
  Vocabulary/Resource/Assets.xcassets/icnflip.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icnflip.imageset/icnflip.png
  Vocabulary/Resource/Assets.xcassets/icnflip.imageset/icnflip@2x.png
  Vocabulary/Resource/Assets.xcassets/icnflip.imageset/icnflip@3x.png
Labels: No Issue

#110 Fix UI Delay
  Vocabulary/MyVoca/VocaForAllViewModel.swift
Labels: No Issue

#107 [1.0.0]
  PoingVocaSubsystem/Network/WordController.swift
  PoingVocaSubsystem/Network/WordService.swift
  PoingVocaSubsystem/VocaCoreDataManager.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordOnlineViewModel.swift
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/AddWord/DetailWordViewModel.swift
  Vocabulary/AddWord/SelectFolderOnlineViewModel.swift
  Vocabulary/AddWord/SelectOnlineViewModel.swift
  Vocabulary/AddWord/SelectViewModel.swift
  Vocabulary/MyVoca/MyVocaOnlineViewModel.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaViewModel.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/PoingDebug.entitlements
  Vocabulary/Setting/EditMyFolderViewModel.swift
  Vocabulary/VacoForAll/SelectFolderViewController.swift
Labels: 🧾 기능개발

#112 [UI] Fix Popup View.
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/Alert/CancelPopupViewController.swift
  Vocabulary/AddWord/Alert/SuccessPopUpViewController.swift
  Vocabulary/AddWord/DetailWordViewController.swift
Labels: UI

#114 Fix speaker animation bug
  PoingDesignSystem/PulseAnimation.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/PoingDebug.entitlements
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/icVoice.png
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/icVoice@2x.png
  Vocabulary/Resource/Assets.xcassets/icVoice.imageset/icVoice@3x.png
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/icVoiceSpeaking.png
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/icVoiceSpeaking@2x.png
  Vocabulary/Resource/Assets.xcassets/icVoiceSpeaking.imageset/icVoiceSpeaking@3x.png
Labels: UI, 🐛 버그

#116 [Fix Feature]
  PoingDesignSystem/PopupViewController.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordViewController.swift
Labels: Refactoring

#117 [115] Design QA
  Vocabulary/Resource/Assets.xcassets/btnGame.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/btnGame.imageset/btnGame.png
  Vocabulary/Resource/Assets.xcassets/btnGame.imageset/btnGame@2x.png
  Vocabulary/Resource/Assets.xcassets/btnGame.imageset/btnGame@3x.png
  Vocabulary/Resource/Assets.xcassets/emptyFace.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/emptyFace.imageset/emptyFace.png
  Vocabulary/Resource/Assets.xcassets/emptyFace.imageset/emptyFace@2x.png
  Vocabulary/Resource/Assets.xcassets/emptyFace.imageset/emptyFace@3x.png
  Vocabulary/Resource/Assets.xcassets/icDelete.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icDelete.imageset/icDelete.png
  Vocabulary/Resource/Assets.xcassets/icDelete.imageset/icDelete@2x.png
  Vocabulary/Resource/Assets.xcassets/icDelete.imageset/icDelete@3x.png
  Vocabulary/Setting/EditMyVocaFolderViewController.swift
  Vocabulary/Setting/MyFolderDetailViewController.swift
Labels: UI

#118 Login network
  PoingVocaSubsystem/Network/EveryVocabularyController.swift
  PoingVocaSubsystem/Network/EveryVocabularyService.swift
  PoingVocaSubsystem/Network/FolderController.swift
  PoingVocaSubsystem/Network/FolderService.swift
  PoingVocaSubsystem/Network/UserController.swift
  PoingVocaSubsystem/Network/UserInfo.swift
  PoingVocaSubsystem/Network/UserService.swift
  PoingVocaSubsystem/Network/Utills/BaseManager.swift
  PoingVocaSubsystem/Network/Utills/ServerURL.swift
  PoingVocaSubsystem/Network/WordController.swift
  PoingVocaSubsystem/Network/WordService.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AppDelegate.swift
  Vocabulary/Base.lproj/LaunchScreen.storyboard
  Vocabulary/Login/AppleLoginHelper.swift
  Vocabulary/Login/LoginViewController.swift
  Vocabulary/MyVoca/MyVocaOnlineViewModel.swift
  Vocabulary/Setting/SettingMyInfoCell.swift
  Vocabulary/Setting/SettingViewController.swift
  Vocabulary/SignUp/SignInNameViewController.swift
  Vocabulary/SignUp/SignUpNameViewController.swift
  Vocabulary/Splash/Splash.storyboard
  Vocabulary/Splash/SplashViewController.swift
  Vocabulary/Utills/ModeConfig.swift
  Vocabulary/Utills/UserDefaults+.swift
Labels: 🧾 기능개발

#121 [#120] Fix major bugs
  PoingVocaSubsystem/Network/FolderController.swift
  PoingVocaSubsystem/Utills/Notification.Name+.swift
  VocaGame/SelectFolderViewController.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordOnlineViewModel.swift
  Vocabulary/MyVoca/MyVocaGroupReusableView.swift
  Vocabulary/MyVoca/MyVocaOnlineViewModel.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/VacoForAll/VocaForAllDetailViewModel.swift
Labels: 🐛 버그

#123 [Feature] Add Word Pagination task
  PoingVocaSubsystem/Network/WordController.swift
  PoingVocaSubsystem/Network/WordService.swift
  PoingVocaSubsystem/Utills/Notification.Name+.swift
  Vocabulary/AddWord/DetailWordOnlineViewModel.swift
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/MyVoca/MyVocaOnlineViewModel.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaViewModel.swift
  Vocabulary/Setting/EditMyVocaFolderCell.swift
  Vocabulary/Setting/MyProfileViewController.swift
Labels: 🧾 기능개발

#124 [Fix Bug] Fix minor Bug #122
  PoingDesignSystem/DeleteUserPopupViewController.swift
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/AddWord/SelectOnlineViewModel.swift
  Vocabulary/AddWord/TakePictureController.swift
  Vocabulary/Setting/MyProfileViewController.swift
  Vocabulary/VacoForAll/SelectFolderViewController.swift
Labels: UI, 🐛 버그

#125 [#122] Fix bugs
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame-acknowledgements.markdown
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame-acknowledgements.plist
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame.debug.xcconfig
  Pods/Target Support Files/Pods-VocaGame/Pods-VocaGame.release.xcconfig
  PoingDesignSystem/DeleteUserPopupViewController.swift
  PoingDesignSystem/PopupViewController.swift
  PoingVocaSubsystem/Network/EveryVocaResponse.swift
  PoingVocaSubsystem/Network/FolderController.swift
  PoingVocaSubsystem/Network/WordController.swift
  PoingVocaSubsystem/Network/WordService.swift
  VocaGame/Flip/View/FlipCardView.swift
  VocaGame/Matching/CardCell.swift
  VocaGame/Matching/CardMatchingViewController.swift
  VocaGame/SelectFolderCell.swift
  VocaGame/SelectFolderViewController.swift
  VocaGame/SelectFolderViewModel.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/DetailWordOnlineViewModel.swift
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/Game/GameViewController.swift
  Vocabulary/LoadingView.swift
  Vocabulary/MyVoca/HomeViewController.swift
  Vocabulary/MyVoca/MyVocaOnlineViewModel.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/PoingDebug.entitlements
  Vocabulary/Setting/EditMyFolderOnlineViewModel.swift
  Vocabulary/Setting/EditMyVocaFolderViewController.swift
  Vocabulary/Setting/MyFolderDetailOnlineViewModel.swift
  Vocabulary/Setting/MyFolderDetailViewController.swift
  Vocabulary/Setting/MyProfileViewController.swift
  Vocabulary/Setting/SettingViewController.swift
  Vocabulary/SignUp/SignUpNameViewController.swift
  Vocabulary/Utills/UIAlerController.swift
  Vocabulary/Utills/UIWindow+.swift
  Vocabulary/VacoForAll/SelectFolderViewController.swift
  Vocabulary/VacoForAll/VocaForAllCell.swift
  Vocabulary/VacoForAll/VocaForAllDetailViewController.swift
  Vocabulary/VacoForAll/VocaHeaderView.swift
  Vocabulary/VacoForAll/WordDetailCell.swift
  Vocabulary/Vocabulary.entitlements
Labels: 🐛 버그, 🧾 기능개발

#127 Fix bugs
  PoingVocaSubsystem/Network/UserController.swift
  PoingVocaSubsystem/Network/UserService.swift
  VocaGame/SelectFolderViewController.swift
  Vocabulary/Setting/MyProfileViewController.swift
Labels: 🐛 버그

#126 [Fix] update UIAlertView to UIAlertController
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
Labels: 🐛 버그

#128 Disable dark mode, Fix navigation left button event correctly in FlipGameVC
  PoingDesignSystem/PopupViewController.swift
  PoingDesignSystem/SuccessPopupView.swift
  VocaGame/Flip/Controllers/FlipGameViewController.swift
  Vocabulary/AddWord/DetailWordViewController.swift
  Vocabulary/Info.plist
  Vocabulary/VacoForAll/VocaForAllDetailViewController.swift
Labels: No Issue, 🐛 버그

#132 [#131] Camera Refactoring
  VocaGame/SelectFolderCell.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/TakePictureController.swift
  Vocabulary/Info.plist
  Vocabulary/Setting/MyProfileViewController.swift
  Vocabulary/VacoForAll/SelectFolderViewCell.swift
Labels: Refactoring

#133 Improvements
  PoingVocaSubsystem/Network/UserController.swift
  VocaGame/Flip/Controllers/FlipGameViewController.swift
  VocaGame/Flip/View/StackContainerView.swift
  VocaGame/Guide/GameGuideUtill.swift
  VocaGame/Guide/GuideView.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Login/LoginViewController.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/Resource/Assets.xcassets/GuideiconSwipe.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/GuideiconSwipe.imageset/GuideiconSwipe.png
  Vocabulary/Resource/Assets.xcassets/GuideiconSwipe.imageset/GuideiconSwipe@2x.png
  Vocabulary/Resource/Assets.xcassets/GuideiconSwipe.imageset/GuideiconSwipe@3x.png
  Vocabulary/Resource/Assets.xcassets/GuideiconTouch.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/GuideiconTouch.imageset/GuideiconTouch.png
  Vocabulary/Resource/Assets.xcassets/GuideiconTouch.imageset/GuideiconTouch@2x.png
  Vocabulary/Resource/Assets.xcassets/GuideiconTouch.imageset/GuideiconTouch@3x.png
  Vocabulary/Setting/SettingViewController.swift
Labels: No Issue, UI, 🧾 기능개발

#136 Fix reject issues
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/TakePictureController.swift
  Vocabulary/Info.plist
  Vocabulary/Login/AppleLoginButton.swift
  Vocabulary/Login/AppleLoginHelper.swift
  Vocabulary/Login/LoginViewController.swift
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/iconApple.png
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/iconApple@2x.png
  Vocabulary/Resource/Assets.xcassets/iconApple.imageset/iconApple@3x.png
  Vocabulary/Setting/SettingViewController.swift
  Vocabulary/Splash/SplashViewController.swift
  Vocabulary/Utills/UserDefaults+.swift
Labels: No Issue
