Repository DDD-4/Spark-iOS, pull requests merged in 2020-08, with the labels that each got.

#22 Fix build error
  Vocabulary.xcodeproj/project.pbxproj
Labels: bug

#21 [PreDev] Voca For All UI
  Voca/Voca/ManagedWord+CoreDataProperties.swift
  VocaDesignSystem/VocaDesignSystem.xcodeproj/project.pbxproj
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AddWord/AddWordNavigationView.swift
  Vocabulary/TabbarViewController.swift
  Vocabulary/VacoForAll/Detail/VocaDetailViewController.swift
  Vocabulary/VacoForAll/Detail/WordDetailCell.swift
  Vocabulary/VacoForAll/Detail/WordViewModel.swift
  Vocabulary/VocaForAll/VocaForAllCell.swift
  Vocabulary/VocaForAll/VocaForAllModel.swift
  Vocabulary/VocaForAll/VocaForAllNavigationView.swift
  Vocabulary/VocaForAll/VocaForAllViewController.swift
  Vocabulary/Vocabulary.entitlements
Labels: UI

#24 [Design System] Add Some NavigationView, Add common PopupViewcontroller
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Controllers/FlipGameViewController.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/View/StackContainerView.swift
  VocaDesignSystem/VocaDesignSystem.xcodeproj/project.pbxproj
  VocaDesignSystem/VocaDesignSystem/NavigationView/LeftTitleNavigationView.swift
  VocaDesignSystem/VocaDesignSystem/NavigationView/PopNavigationView.swift
  VocaDesignSystem/VocaDesignSystem/NavigationView/SideNavigationView.swift
  VocaDesignSystem/VocaDesignSystem/NoticePopupViewController.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Game/Flip/FlipViewController.swift
  Vocabulary/MyVoca/EditMyVocaGroupViewController.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/Resource/Assets.xcassets/btnAdd.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/btnAdd.imageset/btnAdd.png
  Vocabulary/Resource/Assets.xcassets/btnAdd.imageset/btnAdd@2x.png
  Vocabulary/Resource/Assets.xcassets/btnAdd.imageset/btnAdd@3x.png
  Vocabulary/Resource/Assets.xcassets/icArrow.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icArrow.imageset/icArrow.png
  Vocabulary/Resource/Assets.xcassets/icArrow.imageset/icArrow@2x.png
  Vocabulary/Resource/Assets.xcassets/icArrow.imageset/icArrow@3x.png
  Vocabulary/TabbarViewController.swift
Labels: UI

#28 [PreDev] Add Delete, Edit Logic for Group
  PoingVocaSubsystem/VocaCoreDataManager.swift
  PoingVocaSubsystem/VocaManager.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/MyVoca/EditMyVocaGroupCell.swift
  Vocabulary/MyVoca/EditMyVocaGroupViewController.swift
  Vocabulary/MyVoca/EditMyVocaGroupViewModel.swift
Labels: Feature

#29 [PreDev] My Page UI
  Vocabulary/My/MyViewController.swift
  Vocabulary/My/SettingSection.swift
  Vocabulary/My/UserinfoHeader.swift
  Vocabulary/My/settingCell.swift
  Vocabulary/TabbarViewController.swift
Labels: UI

#37 [PreDev] Update Add Word UI
  Vocabulary/AddWord/AddWordViewController.swift
  Vocabulary/AddWord/SelectViewModel.swift
  Vocabulary/AddWord/SelectVocaTableViewCell.swift
  Vocabulary/AddWord/SelectVocaViewController.swift
  Vocabulary/AddWord/TakePictureController.swift
Labels: UI

#38 Apply Design guide for Game List And Flip Game
  PoingDesignSystem/CALayer+.swift
  PoingDesignSystem/NoticePopupViewController.swift
  PoingDesignSystem/UIColor+.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Controllers/FlipGameViewController.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Utils/SwipeCardDelegate.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/View/StackContainerView.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/View/SwipeCardView.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/View/SwipeableCardView.swift
  VocaGame/Media.xcassets/Contents.json
  VocaGame/Media.xcassets/icArrow.imageset/Contents.json
  VocaGame/Media.xcassets/icArrow.imageset/icArrow.png
  VocaGame/Media.xcassets/icArrow.imageset/icArrow@2x.png
  VocaGame/Media.xcassets/icArrow.imageset/icArrow@3x.png
  VocaGame/ProgressBarNavigationView.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Game/GameCell.swift
  Vocabulary/Game/GameViewController.swift
  Vocabulary/MyVoca/HomeViewController.swift
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/btnClose.png
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/btnClose@2x.png
  Vocabulary/Resource/Assets.xcassets/btnClose.imageset/btnClose@3x.png
  Vocabulary/Resource/Assets.xcassets/yellowFace.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/yellowFace.imageset/yellowFace.png
  Vocabulary/Resource/Assets.xcassets/yellowFace.imageset/yellowFace@2x.png
  Vocabulary/Resource/Assets.xcassets/yellowFace.imageset/yellowFace@3x.png
Labels: UI

#40 [#39] Apply Matching Game Logic and Design
  PreDev/CardMatching/CardMatching/CardCell.swift
  PreDev/CardMatching/CardMatching/CardMatchingViewController.swift
  PreDev/CardMatching/CardMatching/ViewController.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Controllers/FlipGameViewController.swift
  VocaGame/ProgressBarNavigationView.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Game/GameViewController.swift
Labels: UI

#42 [#41] Apply Custom Font
  PoingDesignSystem/Info.plist
  PoingDesignSystem/Resources/BalsamiqSansBold.ttf
  PoingDesignSystem/UIFont+.swift
  PreDev/CardMatching/CardMatching/CardCell.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/View/SwipeCardView.swift
  VocaGame/Info.plist
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Info.plist
  Vocabulary/MyVoca/MyVocaWordCell.swift
Labels: Feature

#43 [#36] Flip game refactoring
  PoingDesignSystem/UIFont+.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Animations/PresentDetailViewControllerTransitionAnimation.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Controllers/DetailViewController.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Controllers/ViewController.swift
  PreDev/TinderSwipeInterface-Edit_By_HaeunLee/TinderStack/TinderStack/Utils/SwipeCardDelegate.swift
  VocaGame/Flip/Controllers/FlipGameViewController.swift
  VocaGame/Flip/Model/CardsDataModel.swift
  VocaGame/Flip/Utils/FlipCardViewDataSource.swift
  VocaGame/Flip/Utils/FlipCardViewDelegate.swift
  VocaGame/Flip/View/FlipCardView.swift
  VocaGame/Flip/View/StackContainerView.swift
  VocaGame/Matching/CardCell.swift
  VocaGame/Matching/CardMatchingViewController.swift
  VocaGame/Matching/Model/CardMatching.swift
  VocaGame/Matching/Model/ImageWord.swift
  Vocabulary.xcodeproj/project.pbxproj
Labels: Refactoring

#47 Improve CoreData Logic
  PoingVocaSubsystem/Load.xcdatamodeld/Load.xcdatamodel/contents
  PoingVocaSubsystem/LoadCoreDataManager.swift
  PoingVocaSubsystem/VocaCoreDataManager.swift
  PoingVocaSubsystem/VocaManager.swift
  PoingVocaSubsystemTests/PoingVocaSubsystemTests.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/AppDelegate.swift
  Vocabulary/Info.plist
  Vocabulary/MyVoca/MyVocaViewModel.swift
  Vocabulary/Vocabulary.entitlements
Labels: 🐛 버그, 🧾 기능개발

#55 [#53] Miner Design, TTS feature
  PoingDesignSystem/UIColor+.swift
  VocaGame/Matching/CardCell.swift
  VocaGame/Matching/CardMatchingViewController.swift
  VocaGame/Matching/Model/CardMatching.swift
  Vocabulary/Game/GameCell.swift
  Vocabulary/Game/GameViewController.swift
  Vocabulary/MyVoca/MyVocaEmptyCell.swift
  Vocabulary/MyVoca/MyVocaGroupNameCell.swift
  Vocabulary/MyVoca/MyVocaGroupReusableView.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/Resource/Assets.xcassets/btnCloseWhite.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/btnCloseWhite.imageset/btnCloseWhite.png
  Vocabulary/Resource/Assets.xcassets/btnCloseWhite.imageset/btnCloseWhite@2x.png
  Vocabulary/Resource/Assets.xcassets/btnCloseWhite.imageset/btnCloseWhite@3x.png
Labels: UI, 🧾 기능개발

#58 [#56] Change FolderViewController follows new design
  Podfile
  Podfile.lock
  Pods/KeyboardObserver/KeyboardObserver/KeyboardObserver.swift
  Pods/KeyboardObserver/LICENSE
  Pods/KeyboardObserver/README.md
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/KeyboardObserver/KeyboardObserver-Info.plist
  Pods/Target Support Files/KeyboardObserver/KeyboardObserver-dummy.m
  Pods/Target Support Files/KeyboardObserver/KeyboardObserver-prefix.pch
  Pods/Target Support Files/KeyboardObserver/KeyboardObserver-umbrella.h
  Pods/Target Support Files/KeyboardObserver/KeyboardObserver.modulemap
  Pods/Target Support Files/KeyboardObserver/KeyboardObserver.xcconfig
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary-acknowledgements.markdown
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary-acknowledgements.plist
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary-frameworks-Debug-input-files.xcfilelist
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary-frameworks-Debug-output-files.xcfilelist
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary-frameworks-Release-input-files.xcfilelist
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary-frameworks-Release-output-files.xcfilelist
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary-frameworks.sh
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary.debug.xcconfig
  Pods/Target Support Files/Pods-Vocabulary/Pods-Vocabulary.release.xcconfig
  PoingDesignSystem/AccentLineTextField.swift
  PoingDesignSystem/UIColor+.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/My/MyViewController.swift
  Vocabulary/MyVoca/AddFolderViewController.swift
  Vocabulary/MyVoca/AddVocaViewController.swift
  Vocabulary/MyVoca/EditMyVocaGroupViewController.swift
  Vocabulary/Resource/Assets.xcassets/rectCheckboxChecked.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/rectCheckboxChecked.imageset/rectCheckboxChecked.png
  Vocabulary/Resource/Assets.xcassets/rectCheckboxChecked.imageset/rectCheckboxChecked@2x.png
  Vocabulary/Resource/Assets.xcassets/rectCheckboxChecked.imageset/rectCheckboxChecked@3x.png
  Vocabulary/Resource/Assets.xcassets/rectCheckboxDefault.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/rectCheckboxDefault.imageset/rectCheckboxDefault.png
  Vocabulary/Resource/Assets.xcassets/rectCheckboxDefault.imageset/rectCheckboxDefault@2x.png
  Vocabulary/Resource/Assets.xcassets/rectCheckboxDefault.imageset/rectCheckboxDefault@3x.png
  Vocabulary/Utills/String+.swift
Labels: UI

#59 단어 추가 시 이미지 cropping 기능
  Vocabulary/AddWord/AddWordViewController.swift
  Vocabulary/AddWord/TakePictureController.swift
Labels: Refactoring, 🧾 기능개발

#60 update VocaForAllCell UI
  PoingDesignSystem/UIColor+.swift
  Vocabulary/VocaForAll/VocaForAllCell.swift
Labels: Refactoring, UI

#64 [#63] 내 단어장, 모두의 단어장 ViewController 통일 + miner issus
  PoingDesignSystem/Info.plist
  PoingDesignSystem/NavigationView/SideNavigationView.swift
  PoingVocaSubsystem/VocaCoreDataManager.swift
  VocaGame/Info.plist
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary.xcodeproj/xcshareddata/xcschemes/Vocabulary.xcscheme
  Vocabulary/Info.plist
  Vocabulary/My/SettingViewController.swift
  Vocabulary/MyVoca/EditMyVocaGroupViewController.swift
  Vocabulary/MyVoca/EditMyVocaGroupViewModel.swift
  Vocabulary/MyVoca/HomeHeaderView.swift
  Vocabulary/MyVoca/HomeViewController.swift
  Vocabulary/MyVoca/MyVocaGroupReusableView.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/VocaForAllViewModel.swift
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Vocabulary/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Vocabulary/VacoForAll/VocaForAllCell.swift
  Vocabulary/VocaForAll/VocaForAllModel.swift
  Vocabulary/VocaForAll/VocaForAllNavigationView.swift
  Vocabulary/VocaForAll/VocaForAllViewController.swift
Labels: Refactoring

#70 [#69] Add Quicksand-Bold Font
  PoingDesignSystem/Info.plist
  PoingDesignSystem/Resources/Quicksand-Bold.ttf
  PoingDesignSystem/UIFont+.swift
  VocaGame/Info.plist
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Info.plist
  Vocabulary/MyVoca/MyVocaWordCell.swift
Labels: UI

#68 [#67] 내 프로필 UI 개발
  PoingDesignSystem/UIColor+.swift
  PoingDesignSystem/VDSTextField.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/Resource/Assets.xcassets/btnCompleteDesabled.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/btnCompleteDesabled.imageset/btnCompleteDesabled.png
  Vocabulary/Resource/Assets.xcassets/btnCompleteDesabled.imageset/btnCompleteDesabled@2x.png
  Vocabulary/Resource/Assets.xcassets/btnCompleteDesabled.imageset/btnCompleteDesabled@3x.png
  Vocabulary/Resource/Assets.xcassets/icCamera.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/icCamera.imageset/icCamera.png
  Vocabulary/Resource/Assets.xcassets/icCamera.imageset/icCamera@2x.png
  Vocabulary/Resource/Assets.xcassets/icCamera.imageset/icCamera@3x.png
  Vocabulary/Setting/MyProfileViewController.swift
  Vocabulary/Setting/SettingCell.swift
  Vocabulary/Setting/SettingMyInfoCell.swift
  Vocabulary/Setting/SettingSection.swift
  Vocabulary/Setting/SettingViewController.swift
Labels: UI

#66 [1.0.0] update 모두의단어장_2detail_1
  Vocabulary/AppDelegate.swift
  Vocabulary/MyVoca/HomeViewController.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/Resource/Assets.xcassets/btnPhoto.imageset/Contents.json
  Vocabulary/Resource/Assets.xcassets/btnPhoto.imageset/btnPhoto.png
  Vocabulary/Resource/Assets.xcassets/btnPhoto.imageset/btnPhoto@2x.png
  Vocabulary/Resource/Assets.xcassets/btnPhoto.imageset/btnPhoto@3x.png
  Vocabulary/VacoForAll/Detail/DummyVocaDetailViewController.swift
  Vocabulary/VacoForAll/Detail/VocaDetailViewController.swift
  Vocabulary/VacoForAll/Detail/VocaHeaderView.swift
  Vocabulary/VacoForAll/Detail/WordDetailCell.swift
Labels: Refactoring, UI

#72 [#71] 모두의 단어장 Detail Header UI, Fix miner issus
  PoingDesignSystem/NavigationView/SideNavigationView.swift
  PoingVocaSubsystem/DummyData/DummyData.swift
  VocaGame/Flip/View/FlipCardView.swift
  VocaGame/Matching/CardCell.swift
  Vocabulary.xcodeproj/project.pbxproj
  Vocabulary/MyVoca/HomeViewController.swift
  Vocabulary/MyVoca/MyVocaEmptyCell.swift
  Vocabulary/MyVoca/MyVocaGroupReusableView.swift
  Vocabulary/MyVoca/MyVocaViewController.swift
  Vocabulary/MyVoca/MyVocaWordCell.swift
  Vocabulary/Setting/SettingCell.swift
  Vocabulary/Setting/SettingMyInfoCell.swift
  Vocabulary/Setting/SettingViewController.swift
  Vocabulary/VacoForAll/Detail/DummyVocaDetailViewController.swift
  Vocabulary/VacoForAll/Detail/VocaHeaderView.swift
  Vocabulary/VacoForAll/Detail/WordDetailCell.swift
  Vocabulary/VacoForAll/VocaForAllCell.swift
Labels: UI
